paths:
  /api/productsdb:
    get:
      schema:
        type: string
    responses:
      200:
        description: Lista de productos obtenida correctamente
        content:
          aplication/json:
            schema:
              types: object
              properties:
                status:
                  example: succes
                payload:
                  $ref: '#/components/schemas/Products'
      500: 
        description: Error interno del servidor 
  /set/realtimeproducts:
    get:
      schema:
        type: string
    responses:
      200:
        description: Lista de productos obtenida
        content:
          aplication/json:
            schema:
              types: object
              properties:
                status:
                  example: succes
                payload:
                  $ref: '#/components/schemas/Products'
      500: 
        description: Error interno del servidor socket
        summary: Crear
        tags: 
        - Products
        schema:
        properties:
        status:
        type: string
        example: succes
        payload:
        $ref: '#/components/schemas/Products'      
        
components:
  schemas:
    Products:
      type: object
      properties:
          _id:
            type: string
            description: id de mongoDB  
          title:
            type: string
            description: titulo
          description: 
            type: string
            description: descripcion
          price:
            type: number
            description: precio
          category:
            type: string
            description: categoria del producto
          code:
            type: number
            description: codigo
          stock:
            type: number
            description: cantidad de stock
          statusP:
            type: boolean
            description: stock suficiente o no
          thumbnail:
            type: array
            description: lista url de imagenes
          owner:
            type: string
            description: id de session del creador     